-- 株 取引損益アプリ用テーブル
-- Supabase ダッシュボード → SQL Editor にこのファイルの内容を貼り付けて Run してください。

create table if not exists trades (
    id     bigint generated by default as identity primary key,
    date   date    not null,
    name   text    not null,
    baibai text    not null check (baibai in ('買', '売')),
    shares integer not null check (shares > 0),
    price  integer not null check (price > 0)
);

-- RLS（行レベルセキュリティ）を有効にしたうえで、
-- anon キーからの読み書きを許可するポリシーを作成します。
-- ※ URL と anon キーを知っている人は誰でも読み書きできる設定です。
--    個人利用のアプリを想定しています。
alter table trades enable row level security;

drop policy if exists "allow anon select" on trades;
drop policy if exists "allow anon insert" on trades;

create policy "allow anon select" on trades
    for select to anon using (true);

create policy "allow anon insert" on trades
    for insert to anon with check (true);
